[package]
name = "pallet-council"
version = "0.1.0"
edition = "2021"


[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { package = "parity-scale-codec", version = "2.0.0", default-features = false, features = ["derive"] }
log = { version = "0.4.14", default-features = false }
scale-info = { version = "1.0", default-features = false, features = ["derive"] }

sp-core = { version = "4.0.0-dev", default-features = false, path = "../../../../primitives/core" }
sp-io = { version = "4.0.0-dev", default-features = false, path = "../../../../primitives/io" }
sp-runtime = { version = "4.0.0-dev", default-features = false, path = "../../../../primitives/runtime" }
sp-std = { version = "4.0.0-dev", default-features = false, path = "../../../../primitives/std" }

frame-benchmarking = { version = "4.0.0-dev", default-features = false, path = "../../../../frame/benchmarking", optional = true }
frame-support = { version = "4.0.0-dev", default-features = false, path = "../../../../frame/support" }
frame-system = { version = "4.0.0-dev", default-features = false, path = "../../../../frame/system" }
pallet-assets = { version = "4.0.0-dev", default-features = false, path = "../../../../frame/assets" }
pallet-balances = { version = "4.0.0-dev", default-features = false, path = "../../../../frame/balances" }

[dev-dependencies]
pallet-assets = { version = "4.0.0-dev", path = "../../../../frame/assets" }
pallet-balances = { version = "4.0.0-dev", path = "../../../../frame/balances" }


[features]
default = ["std"]
std = [
	"codec/std",
	"log/std",
	"scale-info/std",
	"sp-core/std",
	"sp-io/std",
	"sp-runtime/std",
	"sp-std/std",
	"frame-benchmarking/std",
	"frame-support/std",
	"frame-system/std",
]
runtime-benchmarks = [
	"frame-benchmarking",
	"sp-runtime/runtime-benchmarks",
	"frame-support/runtime-benchmarks",
	"frame-system/runtime-benchmarks",
]
try-runtime = ["frame-support/try-runtime"]
