[package]
name = "polkadot-test-runtime"
version = "0.9.12"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"
build = "build.rs"

[dependencies]
bitvec = { version = "0.20.1", default-features = false, features = ["alloc"] }
parity-scale-codec = { version = "2.3.1", default-features = false, features = ["derive"] }
log = { version = "0.4.14", default-features = false }
rustc-hex = { version = "2.1.0", default-features = false }
scale-info = { version = "1.0", default-features = false, features = ["derive"] }
serde = { version = "1.0.130", default-features = false }
serde_derive = { version = "1.0.117", optional = true }
smallvec = "1.6.1"

authority-discovery-primitives = { package = "sp-authority-discovery", version = "4.0.0-dev", path = "../../../../primitives/authority-discovery", default-features = false }
babe-primitives = { package = "sp-consensus-babe", version = "0.10.0-dev", path = "../../../../primitives/consensus/babe", default-features = false }
beefy-primitives = { version = "4.0.0-dev", path = "../../../../primitives/beefy", default-features = false }
sp-api = { version = "4.0.0-dev", path = "../../../../primitives/api", default-features = false }
inherents = { package = "sp-inherents", version = "4.0.0-dev", path = "../../../../primitives/inherents", default-features = false }
offchain-primitives = { package = "sp-offchain", version = "4.0.0-dev", path = "../../../../primitives/offchain", default-features = false }
sp-std = { version = "4.0.0-dev", path = "../../../../primitives/std", default-features = false }
sp-io = { version = "4.0.0-dev", path = "../../../../primitives/io", default-features = false }
sp-runtime = { version = "4.0.0-dev", path = "../../../../primitives/runtime", default-features = false }
sp-staking = { version = "4.0.0-dev", path = "../../../../primitives/staking", default-features = false }
sp-core = { version = "4.0.0-dev", path = "../../../../primitives/core", default-features = false }
sp-session = { version = "4.0.0-dev", path = "../../../../primitives/session", default-features = false }
sp-version = { version = "4.0.0-dev", path = "../../../../primitives/version", default-features = false }
frame-election-provider-support = { version = "4.0.0-dev", path = "../../../../frame/election-provider-support", default-features = false }
tx-pool-api = { package = "sp-transaction-pool", version = "4.0.0-dev", path = "../../../../primitives/transaction-pool", default-features = false }
block-builder-api = { package = "sp-block-builder", version = "4.0.0-dev", path = "../../../../primitives/block-builder", default-features = false }

pallet-authority-discovery = { version = "4.0.0-dev", path = "../../../../frame/authority-discovery", default-features = false }
pallet-authorship = { version = "4.0.0-dev", path = "../../../../frame/authorship", default-features = false }
pallet-babe = { version = "4.0.0-dev", path = "../../../../frame/babe", default-features = false }
pallet-balances = { version = "4.0.0-dev", path = "../../../../frame/balances", default-features = false }
pallet-transaction-payment = { version = "4.0.0-dev", path = "../../../../frame/transaction-payment", default-features = false }
pallet-transaction-payment-rpc-runtime-api = { version = "4.0.0-dev", path = "../../../../frame/transaction-payment/rpc/runtime-api", default-features = false }
frame-executive = { version = "4.0.0-dev", path = "../../../../frame/executive", default-features = false }
pallet-grandpa = { version = "4.0.0-dev", path = "../../../../frame/grandpa", default-features = false }
pallet-indices = { version = "4.0.0-dev", path = "../../../../frame/indices", default-features = false }
pallet-mmr-primitives = { version = "4.0.0-dev", path = "../../../../frame/merkle-mountain-range/primitives", default-features = false }
pallet-nicks = { version = "4.0.0-dev", path = "../../../../frame/nicks", default-features = false }
pallet-offences = { version = "4.0.0-dev", path = "../../../../frame/offences", default-features = false }
pallet-session = { version = "4.0.0-dev", path = "../../../../frame/session", default-features = false }
frame-support = { version = "4.0.0-dev", path = "../../../../frame/support", default-features = false }
pallet-staking = { version = "4.0.0-dev", path = "../../../../frame/staking", default-features = false }
pallet-staking-reward-curve = { version = "4.0.0-dev", path = "../../../../frame/staking/reward-curve", default-features = false }
frame-system = {version = "4.0.0-dev", path = "../../../../frame/system", default-features = false }
frame-system-rpc-runtime-api = { version = "4.0.0-dev", path = "../../../../frame/system/rpc/runtime-api", default-features = false }
pallet-timestamp = { version = "4.0.0-dev", path = "../../../../frame/timestamp", default-features = false }
pallet-sudo = { version = "4.0.0-dev", path = "../../../../frame/sudo", default-features = false }
pallet-vesting = { version = "4.0.0-dev", path = "../../../../frame/vesting", default-features = false }

runtime-common = { package = "polkadot-runtime-common", path = "../common", default-features = false }
primitives = { package = "polkadot-primitives", path = "../../../../polkadot-primitives", default-features = false }
pallet-xcm = { path = "../../../../xcm/pallet-xcm", default-features = false }
polkadot-parachain = { path = "../../../../parachain", default-features = false }
polkadot-runtime-parachains = { path = "../parachains", default-features = false }
xcm-builder = { path = "../../../../xcm/xcm-builder", default-features = false }
xcm-executor = { path = "../../../../xcm/xcm-executor", default-features = false }
xcm = { path = "../../../../xcm", default-features = false }

[dev-dependencies]
hex-literal = "0.3.3"
tiny-keccak = "2.0.2"
sp-keyring = { path = "../../../../primitives/keyring" }
sp-trie = { path = "../../../../primitives/trie" }
serde_json = "1.0.67"

[build-dependencies]
substrate-wasm-builder = { path = "../../../../utils/wasm-builder" }

[features]
default = ["std"]
no_std = []
only-staking = []
std = [
	"authority-discovery-primitives/std",
	"pallet-authority-discovery/std",
	"bitvec/std",
	"primitives/std",
	"rustc-hex/std",
	"parity-scale-codec/std",
	"scale-info/std",
	"inherents/std",
	"sp-core/std",
	"polkadot-parachain/std",
	"pallet-xcm/std",
	"xcm-builder/std",
	"xcm-executor/std",
	"xcm/std",
	"sp-api/std",
	"tx-pool-api/std",
	"block-builder-api/std",
	"offchain-primitives/std",
	"sp-std/std",
	"sp-io/std",
	"frame-support/std",
	"pallet-authorship/std",
	"pallet-balances/std",
	"pallet-transaction-payment/std",
	"pallet-transaction-payment-rpc-runtime-api/std",
	"frame-executive/std",
	"pallet-grandpa/std",
	"pallet-indices/std",
	"pallet-nicks/std",
	"pallet-offences/std",
	"sp-runtime/std",
	"sp-staking/std",
	"pallet-session/std",
	"pallet-staking/std",
	"frame-system/std",
	"frame-system-rpc-runtime-api/std",
	"pallet-timestamp/std",
	"sp-version/std",
	"pallet-vesting/std",
	"serde_derive",
	"serde/std",
	"pallet-babe/std",
	"babe-primitives/std",
	"sp-session/std",
	"runtime-common/std",
	"log/std",
	"frame-election-provider-support/std",
]
