[package]
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"
name = "xcm-executor-integration-tests"
description = "Integration tests for the XCM Executor"
version = "0.9.12"

[dependencies]
frame-support = { version = "4.0.0-dev", path = "../../../frame/support", default-features = false }
frame-system = { version = "4.0.0-dev", path = "../../../frame/system" }
futures = "0.3.17"
pallet-xcm = { path = "../../pallet-xcm" }
polkadot-test-client = { path = "../../../node/test/client" }
polkadot-test-runtime = { path = "../../../runtime/test-runtime" }
polkadot-test-service = { path = "../../../node/test/service" }
sp-consensus = { version = "4.0.0-dev", path = "../../../primitives/consensus" }
sp-keyring = { version = "4.0.0-dev", path = "../../../primitives/keyring" }
sp-runtime = { version = "4.0.0-dev", path = "../../../primitives/runtime", default-features = false }
sp-state-machine = { version = "4.0.0-dev", path = "../../../primitives/state-machine" }
xcm = { path = "../..", default-features = false }
xcm-executor = { path = ".." }
sp-tracing = { version = "4.0.0-dev", path = "../../../primitives/tracing" }

[features]
default = ["std"]
std = [
	"xcm/std",
	"sp-runtime/std",
	"frame-support/std",
]
