[package]
name = "pallet-ipfs-rpc"
version = "4.0.0-dev"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"
license = "Apache-2.0"
homepage = "https://substrate.dev"
repository = "https://github.com/paritytech/substrate/"
description = "RPC interface for the ipfs storage pallet."
readme = "README.md"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { package = "parity-scale-codec", version = "2.0.0" }
jsonrpc-core = "18.0.0"
jsonrpc-core-client = "18.0.0"
jsonrpc-derive = "18.0.0"
serde = { version = "1.0.126", features = ["derive"] }
serde_json = "1.0.68"
systemstat = "0.1.11"
log = { version = "0.4.14", default-features = false }

sp-api = { version = "4.0.0-dev", path = "../../../../../primitives/api" }
sp-blockchain = { version = "4.0.0-dev", path = "../../../../../primitives/blockchain" }
sp-core = { version = "4.0.0-dev", path = "../../../../../primitives/core" }
sp-rpc = { version = "4.0.0-dev", path = "../../../../../primitives/rpc" }
sp-runtime = { version = "4.0.0-dev", path = "../../../../../primitives/runtime" }
pallet-ipfs-rpc-runtime-api = { version = "4.0.0-dev", path = "./runtime-api" }
