[package]
name = "pallet-updater"
version = "0.1.0"
edition = "2021"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { package = "parity-scale-codec", version = "2.0.0", default-features = false }
scale-info = { version = "1.0", default-features = false, features = ["derive"] }
frame-support = { version = "4.0.0-dev", default-features = false, path = "../../../../frame/support" }
frame-system = { version = "4.0.0-dev", default-features = false, path = "../../../../frame/system" }
frame-benchmarking = { version = "4.0.0-dev", default-features = false, path = "../../../../frame/benchmarking", optional = true }
sp-std = { version = "4.0.0-dev", default-features = false, path = "../../../../primitives/std" }

[dev-dependencies]
sp-core = { version = "4.0.0-dev", path = "../../../../primitives/core", default-features = false }
sp-io = { version = "4.0.0-dev", path = "../../../../primitives/io", default-features = false }
sp-runtime = { version = "4.0.0-dev", path = "../../../../primitives/runtime", default-features = false }

[features]
default = ["std"]
std = [
	"codec/std",
	"scale-info/std",
	"frame-support/std",
	"frame-system/std",
	"frame-benchmarking/std",
]

try-runtime = ["frame-support/try-runtime"]